# Generated by datamodel-codegen from the TethysDash OpenAPI spec.
# Trimmed down to only the models and fields used by this project.

from __future__ import annotations
from typing import Literal, get_args

from pydantic import BaseModel, ConfigDict, Field


class LaxBaseModel(BaseModel):
	model_config = ConfigDict(extra='allow')

class ChartDataElement(LaxBaseModel):
	values: list[float] | None = None
	times: list[int] | None = None

class DeploymentEventInfo(LaxBaseModel):
	unix_time: int | None = Field(None, alias='unixTime')

class DeploymentInfo(LaxBaseModel):
	deployment_id: int | None = Field(None, alias='deploymentId')
	start_event: DeploymentEventInfo | None = Field(None, alias='startEvent')
	recover_event: DeploymentEventInfo | None = Field(None, alias='recoverEvent')

class DeploymentResponse(LaxBaseModel):
	result: DeploymentInfo | None = None

class LatLon(LaxBaseModel):
	lat: float | None = None
	lon: float | None = None

class ScriptArg(LaxBaseModel):
	name: str | None = None
	unit: str | None = None
	value: str | None = None

class WaypointInfo(LaxBaseModel):
	points: list[LatLon] | None = None

class WpInfoResponse(LaxBaseModel):
	result: WaypointInfo | None = None

class WpMissionDescription(LaxBaseModel):
	script_args: list[ScriptArg] | None = Field(None, alias='scriptArgs')
	inserts: list[WpMissionDescription] | None = None

class ScriptDescriptionResponse(LaxBaseModel):
	result: WpMissionDescription | None = None
WpMissionDescription.model_rebuild()  # due to cyclic reference

# -----------------------------------------------------------------------------
# The spec does not define event structures, so these are hand-written to parse
# enough fields for our purposes.

class Fix(LaxBaseModel):
	latitude: float | None = None
	longitude: float | None = None


class Event(LaxBaseModel):
	unix_time: int = Field(alias="unixTime")
	event_type: str | None = Field(default=None, alias="eventType")
	name: str | None = None
	text: str | None = None
	note: str | None = None
	state: int | None = None
	path: str | None = None
	fix: Fix | None = None

	@classmethod
	def event_type_literal(cls) -> str | None:
		"""Return the Literal value of this subclass's event_type field, if any."""
		field = cls.model_fields.get("event_type")
		if field is None:
			return None
		args = get_args(field.annotation)
		if args and isinstance(args[0], str):
			return args[0]
		return None


class LaunchEvent(Event):
	event_type: Literal["launch"] = Field(alias="eventType")


class RecoverEvent(Event):
	event_type: Literal["recover"] = Field(alias="eventType")


class DeployEvent(Event):
	event_type: Literal["deploy"] = Field(alias="eventType")


class GpsFixEvent(Event):
	# parseGPS dereferences .fix.latitude/.longitude directly, so fix is
	# required on this variant.
	event_type: Literal["gpsFix"] = Field(alias="eventType")
	fix: Fix


class ArgoReceiveEvent(Event):
	event_type: Literal["argoReceive"] = Field(alias="eventType")


class NoteEvent(Event):
	event_type: Literal["note"] = Field(alias="eventType")


class LogCriticalEvent(Event):
	event_type: Literal["logCritical"] = Field(alias="eventType")


class LogFaultEvent(Event):
	event_type: Literal["logFault"] = Field(alias="eventType")


class LogImportantEvent(Event):
	event_type: Literal["logImportant"] = Field(alias="eventType")


class CommandEvent(Event):
	event_type: Literal["command"] = Field(alias="eventType")


class SbdReceiveEvent(Event):
	event_type: Literal["sbdReceive"] = Field(alias="eventType")


class DataProcessedEvent(Event):
	event_type: Literal["dataProcessed"] = Field(alias="eventType")


# -----------------------------------------------------------------------------
# This models the shore.asc data entries. It is not actually part of the API
# spec.

class ShoreAscSnapshot(LaxBaseModel):
	# `platform_battery_voltage` and `BPC1>platform_battery_voltage` are kept
	# separate so the legacy Ahi-vs-others split (Ahi reads voltage from BPC1
	# lines, everyone else from the unprefixed lines) can be honored downstream.
	battery_voltage: float | None = None
	battery_voltage_time: int | None = None
	battery_voltage_bpc1: float | None = None
	battery_voltage_bpc1_time: int | None = None
	battery_charge: float | None = None
	battery_charge_time: int | None = None
	flow_rate_ml_per_s: int | None = None
	flow_rate_time: int | None = None
	tracking_ranges_m: list[int] = Field(default_factory=list)
	tracking_times: list[int] = Field(default_factory=list)
